name: Compile Protobufs to Go

on:
  pull_request:
    paths:
      - "proto/**/*.proto"

permissions:
  contents: write
jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    container: jackpar/protoc
    steps:
      - uses: actions/checkout@v2
      - name: "Generate for Golang"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/protoc.sh"
          ./scripts/protoc.sh