name: Compile Protobufs

on:
  pull_request:
    paths:
      - "proto/**/*.proto"

permissions:
  contents: write
jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - uses: actions/checkout@v2
      - name: "Generate for Golang with Docker"
        uses: docker://jackpar/protoc
        with:
          args: |
            bash -c "
              chmod +x /workspace/scripts/protoc.sh &&
              /workspace/scripts/protoc.sh
            "
        env:
          GITHUB_WORKSPACE: /workspace
        volumes:
          - "${{ github.workspace }}:/workspace"